server:
  port: 8081
spring:
  application:
    name: msc-provider-depart
  cloud:
    nacos:
      discovery:
#        server-addr: 192.168.254.128:8848
        server-addr: localhost:8848
        # 集群
        # server-addr: 192.168.254.128:8848,192.168.254.130:8848,192.168.254.132:8848
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.254.128:3306/test?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 123456
logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.yw: debug