server:
  port: 9000
spring:
  application:
    name: msc-gateway-depart
  cloud:
    nacos:
      discovery:
#        server-addr: 192.168.254.128:8848
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: ribbon_route
        predicates:
        - Path=/provider/depart/**
        uri: lb://msc-provider-depart
