server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
#      - id: addRequestHeader_filter
#      - id: addRequestParameter_filter
#      - id: addResponseHeader_filter
#      - id: prefixPath_filter
#      - id: stripPrefix_filter
#      - id: rewritePath_filter
#      - id: circuitBreaker_filter
      - id: requestRateLimiter_filter
        uri: http://localhost:8080
        predicates:
        - Path=/**
        filters:
#        - AddRequestHeader=X-Request-Color, blue
#        - AddRequestParameter=color, blue
#        - AddResponseHeader=X-Response-Color, blue
#        - PrefixPath=/info
#        - StripPrefix=2
#        - RewritePath=/red(?<segment>/?.*), $\{segment}
#        - name: CircuitBreaker
#          args:
#            name: myCircuitBreaker
#            fallbackUri: forward:/fallback
        - name: RequestRateLimiter
          args:
            key-resolver: "#{@keyResolver}"
            redis-rate-limiter.replenishRate: 2
            redis-rate-limiter.burstCapacity: 5
            redis-rate-limiter.requestedTokens: 1
